CREATE TABLE [dbo].[Sheet1$] (
    [WAREHOUSE_PARENT]  NVARCHAR (255) NULL,
    [ZONE]              NVARCHAR (255) NULL,
    [LOCATION_SPOT]     NVARCHAR (255) NULL,
    [SPOT_TYPE]         NVARCHAR (255) NULL,
    [SPOT_ORDERBY]      FLOAT (53)     NULL,
    [SPOT_AISLE]        FLOAT (53)     NULL,
    [SPOT_COLUMN]       NVARCHAR (255) NULL,
    [SPOT_LEVEL]        NVARCHAR (255) NULL,
    [SPOT_PARTITION]    FLOAT (53)     NULL,
    [SPOT_LABEL]        NVARCHAR (255) NULL,
    [ALLOW_PICKING]     FLOAT (53)     NULL,
    [ALLOW_STORAGE]     FLOAT (53)     NULL,
    [ALLOW_REALLOC]     FLOAT (53)     NULL,
    [AVAILABLE]         FLOAT (53)     NULL,
    [LINE_ID]           NVARCHAR (255) NULL,
    [SPOT_LINE]         NVARCHAR (255) NULL,
    [LOCATION_OVERLOAD] NVARCHAR (255) NULL,
    [MAX_MT2_OCCUPANCY] FLOAT (53)     NULL,
    [MAX_WEIGHT]        FLOAT (53)     NULL
);

