CREATE TABLE [dbo].[SOD_TEMPORAL] (
    [SALES_ORDER_ID]             INT             IDENTITY (1, 1) NOT NULL,
    [TERMS]                      VARCHAR (15)    NULL,
    [POSTED_DATETIME]            DATETIME        NULL,
    [CLIENT_ID]                  VARCHAR (50)    NULL,
    [POS_TERMINAL]               VARCHAR (25)    NULL,
    [GPS_URL]                    VARCHAR (150)   NULL,
    [TOTAL_AMOUNT]               NUMERIC (18, 6) NULL,
    [STATUS]                     INT             NULL,
    [POSTED_BY]                  VARCHAR (25)    NULL,
    [IMAGE_1]                    VARCHAR (MAX)   NULL,
    [IMAGE_2]                    VARCHAR (MAX)   NULL,
    [IMAGE_3]                    VARCHAR (MAX)   NULL,
    [DEVICE_BATTERY_FACTOR]      INT             NULL,
    [VOID_DATETIME]              DATETIME        NULL,
    [VOID_REASON]                VARCHAR (25)    NULL,
    [VOID_NOTES]                 VARCHAR (MAX)   NULL,
    [VOIDED]                     INT             NULL,
    [CLOSED_ROUTE_DATETIME]      DATETIME        NULL,
    [IS_ACTIVE_ROUTE]            INT             NULL,
    [GPS_EXPECTED]               VARCHAR (MAX)   NULL,
    [DELIVERY_DATE]              DATETIME        NULL,
    [SALES_ORDER_ID_HH]          INT             NULL,
    [ATTEMPTED_WITH_ERROR]       INT             NULL,
    [IS_POSTED_ERP]              INT             NULL,
    [POSTED_ERP]                 DATETIME        NULL,
    [POSTED_RESPONSE]            VARCHAR (150)   NULL,
    [IS_PARENT]                  INT             NULL,
    [REFERENCE_ID]               VARCHAR (150)   NULL,
    [WAREHOUSE]                  VARCHAR (50)    NULL,
    [TIMES_PRINTED]              INT             NULL,
    [DOC_SERIE]                  VARCHAR (100)   NULL,
    [DOC_NUM]                    INT             NULL,
    [IS_VOID]                    INT             NULL,
    [SALES_ORDER_TYPE]           VARCHAR (250)   NULL,
    [DISCOUNT]                   NUMERIC (18, 6) NULL,
    [IS_DRAFT]                   INT             NULL,
    [ASSIGNED_BY]                VARCHAR (50)    NULL,
    [TASK_ID]                    INT             NULL,
    [COMMENT]                    VARCHAR (250)   NULL,
    [ERP_REFERENCE]              VARCHAR (256)   NULL,
    [PAYMENT_TIMES_PRINTED]      INT             NULL,
    [PAID_TO_DATE]               NUMERIC (18, 6) NULL,
    [TO_BILL]                    INT             NULL,
    [HAVE_PICKING]               INT             NULL,
    [AUTHORIZED]                 INT             NOT NULL,
    [AUTHORIZED_BY]              VARCHAR (50)    NULL,
    [AUTHORIZED_DATE]            DATETIME        NULL,
    [DISCOUNT_BY_GENERAL_AMOUNT] NUMERIC (18, 6) NULL,
    [IS_READY_TO_SEND]           INT             NULL,
    [IS_SENDING]                 INT             NULL,
    [LAST_UPDATE_IS_SENDING]     DATETIME        NULL,
    [SERVER_POSTED_DATETIME]     DATETIME        NOT NULL,
    [DEVICE_NETWORK_TYPE]        VARCHAR (15)    NULL,
    [IS_POSTED_OFFLINE]          INT             NOT NULL
);


GO
CREATE NONCLUSTERED INDEX [IDX_TEMPORAL]
    ON [dbo].[SOD_TEMPORAL]([POS_TERMINAL] ASC, [AUTHORIZED] ASC, [IS_READY_TO_SEND] ASC, [POSTED_DATETIME] ASC)
    INCLUDE([SALES_ORDER_ID], [CLIENT_ID], [GPS_URL], [TOTAL_AMOUNT], [POSTED_BY], [IMAGE_1], [IMAGE_2], [DELIVERY_DATE], [IS_POSTED_ERP], [POSTED_RESPONSE], [IS_PARENT], [REFERENCE_ID], [WAREHOUSE], [DOC_SERIE], [DOC_NUM], [IS_VOID], [SALES_ORDER_TYPE], [DISCOUNT], [IS_DRAFT], [ASSIGNED_BY]);

