CREATE TABLE [acsa].[SONDA_PACK_UNIT] (
    [PACK_UNIT]             INT           IDENTITY (1, 1) NOT NULL,
    [CODE_PACK_UNIT]        VARCHAR (25)  NULL,
    [DESCRIPTION_PACK_UNIT] VARCHAR (250) NULL,
    [LAST_UPDATE]           DATETIME      NULL,
    [LAST_UPDATE_BY]        VARCHAR (25)  NULL,
    [UM_ENTRY]              NUMERIC (18)  NULL,
    [ORDER]                 INT           NULL,
    CONSTRAINT [PK__SONDA_PA__B64AD38F46FB9C1F] PRIMARY KEY CLUSTERED ([PACK_UNIT] ASC),
    CONSTRAINT [UQ__SONDA_PA__2C588EED489F0866] UNIQUE NONCLUSTERED ([CODE_PACK_UNIT] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IDX_SONDA_PACK_UNIT_CODE_PACK_UNIT_DESCRIPTION_PACK_UNIT]
    ON [acsa].[SONDA_PACK_UNIT]([PACK_UNIT] ASC, [DESCRIPTION_PACK_UNIT] ASC);

