CREATE TABLE [acsa].[SONDA_POS_INVOICE_HEADER_HIST] (
    [INVOICE_ID]             INT             NOT NULL,
    [TERMS]                  VARCHAR (15)    NULL,
    [POSTED_DATETIME]        DATETIME        NULL,
    [CLIENT_ID]              VARCHAR (50)    NULL,
    [POS_TERMINAL]           VARCHAR (25)    NULL,
    [GPS_URL]                VARCHAR (150)   NULL,
    [TOTAL_AMOUNT]           MONEY           NULL,
    [STATUS]                 INT             NULL,
    [POSTED_BY]              VARCHAR (25)    NULL,
    [IMAGE_1]                VARCHAR (MAX)   NULL,
    [IMAGE_2]                VARCHAR (MAX)   NULL,
    [IMAGE_3]                VARCHAR (MAX)   NULL,
    [IS_POSTED_OFFLINE]      INT             NULL,
    [INVOICED_DATETIME]      DATETIME        NULL,
    [DEVICE_BATTERY_FACTOR]  INT             NULL,
    [CDF_INVOICENUM]         INT             NULL,
    [CDF_DOCENTRY]           INT             NULL,
    [CDF_SERIE]              VARCHAR (50)    NOT NULL,
    [CDF_NIT]                VARCHAR (25)    NULL,
    [CDF_NOMBRECLIENTE]      VARCHAR (150)   NULL,
    [CDF_RESOLUCION]         VARCHAR (50)    NOT NULL,
    [CDF_POSTED_ERP]         DATETIME        NULL,
    [IS_CREDIT_NOTE]         INT             NOT NULL,
    [VOID_DATETIME]          DATETIME        NULL,
    [CDF_PRINTED_COUNT]      INT             NULL,
    [VOID_REASON]            VARCHAR (250)   NULL,
    [VOID_NOTES]             VARCHAR (MAX)   NULL,
    [VOIDED_INVOICE]         INT             NULL,
    [CLOSED_ROUTE_DATETIME]  DATETIME        NULL,
    [CLEARING_DATETIME]      DATETIME        NULL,
    [IS_ACTIVE_ROUTE]        INT             NULL,
    [SOURCE_CODE]            NUMERIC (18)    NULL,
    [GPS_EXPECTED]           VARCHAR (MAX)   NULL,
    [ATTEMPTED_WITH_ERROR]   INT             NULL,
    [IS_POSTED_ERP]          INT             NULL,
    [POSTED_ERP]             DATETIME        NULL,
    [POSTED_RESPONSE]        VARCHAR (150)   NULL,
    [IS_DRAFT]               INT             NULL,
    [ERP_REFERENCE]          VARCHAR (256)   NULL,
    [CONSIGNMENT_ID]         INT             NULL,
    [LIQUIDATION_ID]         BIGINT          NULL,
    [INITIAL_TASK_IMAGE]     VARCHAR (MAX)   NULL,
    [IN_ROUTE_PLAN]          INT             NULL,
    [ID]                     INT             IDENTITY (1, 1) NOT NULL,
    [IS_READY_TO_SEND]       INT             NULL,
    [IS_SENDING]             INT             NULL,
    [LAST_UPDATE_IS_SENDING] DATETIME        NULL,
    [HANDLE_TAX]             INT             NULL,
    [TAX_PERCENT]            NUMERIC (18, 6) NULL,
    [SIGNATURE]              VARCHAR (MAX)   NULL,
    [TELEPHONE_NUMBER]       VARCHAR (50)    NULL,
    [IS_FROM_DELIVERY_NOTE]  INT             NULL,
    [IT_EXPORTED_TO_XML]     INT             NULL,
    [IS_EXPORTED_TO_XML]     INT             NULL,
    [DISCOUNT]               NUMERIC (18, 6) NOT NULL,
    [COMMENT]                VARCHAR (250)   NULL,
    [DUE_DATE]               DATETIME        NOT NULL,
    [CREDIT_AMOUNT]          NUMERIC (18, 6) NOT NULL,
    [CASH_AMOUNT]            NUMERIC (18, 6) NOT NULL,
    [PAID_TO_DATE]           NUMERIC (18, 6) NOT NULL
);

