CREATE TABLE [acsa].[SONDA_POS_INVOICE_HEADER_T] (
    [INVOICE_ID]             VARCHAR (50)    NOT NULL,
    [TERMS]                  VARCHAR (15)    NULL,
    [POSTED_DATETIME]        DATETIME        NULL,
    [CLIENT_ID]              VARCHAR (50)    NULL,
    [POS_TERMINAL]           VARCHAR (25)    NULL,
    [GPS_URL]                VARCHAR (150)   NULL,
    [TOTAL_AMOUNT]           MONEY           NULL,
    [STATUS]                 VARCHAR (50)    NULL,
    [POSTED_BY]              VARCHAR (25)    NULL,
    [IMAGE_1]                VARCHAR (MAX)   NULL,
    [IMAGE_2]                VARCHAR (MAX)   NULL,
    [IMAGE_3]                VARCHAR (MAX)   NULL,
    [IS_POSTED_OFFLINE]      VARCHAR (50)    NULL,
    [INVOICED_DATETIME]      DATETIME        NULL,
    [DEVICE_BATTERY_FACTOR]  VARCHAR (50)    NULL,
    [CDF_INVOICENUM]         VARCHAR (50)    NULL,
    [CDF_DOCENTRY]           VARCHAR (50)    NULL,
    [CDF_SERIE]              VARCHAR (50)    NOT NULL,
    [CDF_NIT]                VARCHAR (30)    NULL,
    [CDF_NOMBRECLIENTE]      VARCHAR (150)   NULL,
    [CDF_RESOLUCION]         VARCHAR (50)    NOT NULL,
    [CDF_POSTED_ERP]         DATETIME        NULL,
    [IS_CREDIT_NOTE]         VARCHAR (50)    NOT NULL,
    [VOID_DATETIME]          DATETIME        NULL,
    [CDF_PRINTED_COUNT]      VARCHAR (50)    NULL,
    [VOID_REASON]            VARCHAR (250)   NULL,
    [VOID_NOTES]             VARCHAR (MAX)   NULL,
    [VOIDED_INVOICE]         VARCHAR (50)    NULL,
    [CLOSED_ROUTE_DATETIME]  DATETIME        NULL,
    [CLEARING_DATETIME]      DATETIME        NULL,
    [IS_ACTIVE_ROUTE]        VARCHAR (50)    NULL,
    [SOURCE_CODE]            NUMERIC (18)    NULL,
    [GPS_EXPECTED]           VARCHAR (MAX)   NULL,
    [ATTEMPTED_WITH_ERROR]   VARCHAR (50)    NULL,
    [IS_POSTED_ERP]          VARCHAR (50)    NULL,
    [POSTED_ERP]             DATETIME        NULL,
    [POSTED_RESPONSE]        VARCHAR (MAX)   NULL,
    [IS_DRAFT]               VARCHAR (50)    NULL,
    [ERP_REFERENCE]          VARCHAR (256)   NULL,
    [CONSIGNMENT_ID]         VARCHAR (50)    NULL,
    [LIQUIDATION_ID]         BIGINT          NULL,
    [INITIAL_TASK_IMAGE]     VARCHAR (MAX)   NULL,
    [IN_ROUTE_PLAN]          VARCHAR (50)    NULL,
    [ID]                     INT             IDENTITY (1, 1) NOT NULL,
    [IS_READY_TO_SEND]       VARCHAR (50)    NULL,
    [IS_SENDING]             VARCHAR (50)    NULL,
    [LAST_UPDATE_IS_SENDING] DATETIME        NULL,
    [HANDLE_TAX]             VARCHAR (50)    NULL,
    [TAX_PERCENT]            NUMERIC (18, 6) NULL,
    [SIGNATURE]              VARCHAR (MAX)   NULL,
    [TELEPHONE_NUMBER]       VARCHAR (50)    NULL,
    [IS_FROM_DELIVERY_NOTE]  VARCHAR (50)    NULL,
    [IT_EXPORTED_TO_XML]     VARCHAR (50)    NULL,
    [IS_EXPORTED_TO_XML]     VARCHAR (50)    NULL,
    [DISCOUNT]               NUMERIC (18, 6) NULL,
    [COMMENT]                VARCHAR (250)   NULL,
    [DUE_DATE]               DATETIME        NULL,
    [CREDIT_AMOUNT]          NUMERIC (18, 6) NULL,
    [CASH_AMOUNT]            NUMERIC (18, 6) NULL,
    [PAID_TO_DATE]           NUMERIC (18, 6) NULL,
    [TASK_ID]                VARCHAR (50)    NULL,
    [USER_AMOUNT]            DECIMAL (18, 6) NULL,
    [CHANGE]                 DECIMAL (18, 6) NULL,
    [INVOICE_XML]            XML             NULL
);

