CREATE TABLE [acsa].[SWIFT_CURRENCY] (
    [CURRENCY_ID]     INT           IDENTITY (1, 1) NOT NULL,
    [CODE_CURRENCY]   VARCHAR (50)  NOT NULL,
    [NAME_CURRENCY]   VARCHAR (250) NOT NULL,
    [SYMBOL_CURRENCY] VARCHAR (5)   NOT NULL,
    [IS_DEFAULT]      INT           NOT NULL,
    CONSTRAINT [PK__SWIFT_CU__B7625E1B472FB1FB] PRIMARY KEY CLUSTERED ([CURRENCY_ID] ASC),
    CONSTRAINT [UQ__SWIFT_CU__313EF206550768E8] UNIQUE NONCLUSTERED ([CODE_CURRENCY] ASC)
);

