CREATE TABLE [acsa].[SWIFT_POLYGON_POINT] (
    [POLYGON_ID] INT           NOT NULL,
    [POSITION]   INT           NOT NULL,
    [LATITUDE]   VARCHAR (250) NOT NULL,
    [LONGITUDE]  VARCHAR (250) NOT NULL,
    PRIMARY KEY CLUSTERED ([POLYGON_ID] ASC, [POSITION] ASC),
    CONSTRAINT [FK__SWIFT_POL__POLYG__5D56B96F] FOREIGN KEY ([POLYGON_ID]) REFERENCES [acsa].[SWIFT_POLYGON] ([POLYGON_ID])
);

