CREATE TABLE [acsa].[SWIFT_CUSTOMER_CHANGE] (
    [CUSTOMER]               INT           IDENTITY (1, 1) NOT NULL,
    [CODE_CUSTOMER]          VARCHAR (50)  NOT NULL,
    [PHONE_CUSTOMER]         VARCHAR (50)  NOT NULL,
    [ADRESS_CUSTOMER]        VARCHAR (250) NOT NULL,
    [CONTACT_CUSTOMER]       VARCHAR (50)  NOT NULL,
    [GPS]                    VARCHAR (50)  NOT NULL,
    [POSTED_DATETIME]        DATETIME      NOT NULL,
    [POSTED_BY]              VARCHAR (50)  NOT NULL,
    [CODE_ROUTE]             VARCHAR (50)  NOT NULL,
    [STATUS]                 VARCHAR (50)  CONSTRAINT [DF__SWIFT_CUS__STATU__37461F20] DEFAULT ('NEW') NULL,
    [STATUS_CHANGE_BY]       VARCHAR (250) NULL,
    [STATUS_CHANGE_DATETIME] DATETIME      NULL,
    [ATTEMPTED_WITH_ERROR]   INT           NULL,
    [IS_POSTED_ERP]          INT           NULL,
    [POSTED_ERP]             DATETIME      NULL,
    [POSTED_RESPONSE]        VARCHAR (150) NULL,
    [LAST_UPDATE]            DATETIME      NULL,
    [LAST_UPDATE_BY]         VARCHAR (250) NULL,
    [TAX_ID]                 VARCHAR (50)  NULL,
    [INVOICE_NAME]           VARCHAR (100) NULL,
    [CUSTOMER_NAME]          VARCHAR (250) NULL,
    [NEW_CUSTOMER_NAME]      VARCHAR (250) NULL,
    [OWNER]                  VARCHAR (50)  NULL,
    [OWNER_ID]               VARCHAR (50)  NULL,
    [DEPARTMENT]             VARCHAR (250) CONSTRAINT [DF__SWIFT_CUS__DEPAR__383A4359] DEFAULT ('NO ESPECIFICADO') NULL,
    [MUNICIPALITY]           VARCHAR (250) CONSTRAINT [DF__SWIFT_CUS__MUNIC__392E6792] DEFAULT ('NO ESPECIFICADO') NULL,
    [COLONY]                 VARCHAR (250) CONSTRAINT [DF__SWIFT_CUS__COLON__3A228BCB] DEFAULT ('NO ESPECIFICADO') NULL,
    [SERVER_POSTED_DATETIME] DATETIME      CONSTRAINT [DF__SWIFT_CUS__SERVE__3B16B004] DEFAULT (getdate()) NOT NULL,
    [DEVICE_NETWORK_TYPE]    VARCHAR (15)  NULL,
    [IS_POSTED_OFFLINE]      INT           CONSTRAINT [DF__SWIFT_CUS__IS_PO__3C0AD43D] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_CUSTOMER_SWIFT_CUSTOMER_CHANGE] PRIMARY KEY CLUSTERED ([CUSTOMER] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_CUSTOMER_CHANGE_CODE_CUSTOMER_POSTED_DATETIME]
    ON [acsa].[SWIFT_CUSTOMER_CHANGE]([CODE_CUSTOMER] ASC, [POSTED_DATETIME] ASC);


GO
CREATE NONCLUSTERED INDEX [INDEX_CODE_CUSTOMER_SWIFT_CUSTOMER_CHANGE]
    ON [acsa].[SWIFT_CUSTOMER_CHANGE]([CODE_CUSTOMER] ASC);

