CREATE TABLE [acsa].[SWIFT_DISCOUNT_LIST] (
    [DISCOUNT_LIST_ID]   INT           IDENTITY (1, 1) NOT NULL,
    [NAME_DISCOUNT_LIST] VARCHAR (250) NULL,
    [CODE_ROUTE]         VARCHAR (50)  NULL,
    CONSTRAINT [PK__SWIFT_DI__19692FBEDBC226FF] PRIMARY KEY CLUSTERED ([DISCOUNT_LIST_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_DISCOUNT_LIST_CODE_ROUTE]
    ON [acsa].[SWIFT_DISCOUNT_LIST]([CODE_ROUTE] ASC)
    INCLUDE([DISCOUNT_LIST_ID]);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_DISCOUNT_LIST_CODE_ROUTE_NAME_DISCOUNT_LIST]
    ON [acsa].[SWIFT_DISCOUNT_LIST]([CODE_ROUTE] ASC, [NAME_DISCOUNT_LIST] ASC)
    INCLUDE([DISCOUNT_LIST_ID]);

