CREATE TABLE [acsa].[SWIFT_PROMO_BONUS_BY_GENERAL_AMOUNT] (
    [PROMO_BONUS_BY_GENERAL_AMOUNT_ID] INT             IDENTITY (1, 1) NOT NULL,
    [PROMO_ID]                         INT             NOT NULL,
    [LOW_LIMIT]                        NUMERIC (18, 6) NOT NULL,
    [HIGH_LIMIT]                       NUMERIC (18, 6) NOT NULL,
    [CODE_SKU_BONUS]                   VARCHAR (50)    NOT NULL,
    [PACK_UNIT_BONUS]                  INT             NULL,
    [BONUS_QTY]                        NUMERIC (18)    NOT NULL,
    [LAST_UPDATE]                      DATETIME        DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([PROMO_BONUS_BY_GENERAL_AMOUNT_ID] ASC),
    CONSTRAINT [FK__SWIFT_PRO__PACK___630F92C5] FOREIGN KEY ([PACK_UNIT_BONUS]) REFERENCES [acsa].[SONDA_PACK_UNIT] ([PACK_UNIT]),
    CONSTRAINT [FK__SWIFT_PRO__PROMO__6403B6FE] FOREIGN KEY ([PROMO_ID]) REFERENCES [acsa].[SWIFT_PROMO] ([PROMO_ID]),
    UNIQUE NONCLUSTERED ([PROMO_ID] ASC, [LOW_LIMIT] ASC, [CODE_SKU_BONUS] ASC, [PACK_UNIT_BONUS] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PROMO_BONUS_BY_GENERAL_AMOUNT_LAST_UPDATE]
    ON [acsa].[SWIFT_PROMO_BONUS_BY_GENERAL_AMOUNT]([LAST_UPDATE] ASC);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PROMO_BONUS_BY_GENERAL_AMOUNT_PROMO_ID_LOW_LIMIT_HIGH_LIMIT]
    ON [acsa].[SWIFT_PROMO_BONUS_BY_GENERAL_AMOUNT]([PROMO_ID] ASC)
    INCLUDE([BONUS_QTY], [CODE_SKU_BONUS], [LOW_LIMIT], [HIGH_LIMIT], [PACK_UNIT_BONUS], [PROMO_BONUS_BY_GENERAL_AMOUNT_ID]);

