CREATE TABLE [acsa].[SWIFT_PROMO_BONUS_BY_MULTIPLE] (
    [PROMO_BONUS_BY_MULTIPLE_ID] INT          IDENTITY (1, 1) NOT NULL,
    [PROMO_ID]                   INT          NOT NULL,
    [CODE_SKU]                   VARCHAR (50) NOT NULL,
    [PACK_UNIT]                  INT          NULL,
    [MULTIPLE]                   NUMERIC (18) NOT NULL,
    [CODE_SKU_BONUS]             VARCHAR (50) NOT NULL,
    [PACK_UNIT_BONUS]            INT          NULL,
    [BONUS_QTY]                  NUMERIC (18) NOT NULL,
    [LAST_UPDATE]                DATETIME     CONSTRAINT [DF__SWIFT_PRO__LAST___166F3B3A] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK__SWIFT_PR__44E89FA8FF9A3CC3] PRIMARY KEY CLUSTERED ([PROMO_BONUS_BY_MULTIPLE_ID] ASC),
    CONSTRAINT [FK__SWIFT_PRO__PACK___64F7DB37] FOREIGN KEY ([PACK_UNIT]) REFERENCES [acsa].[SONDA_PACK_UNIT] ([PACK_UNIT]),
    CONSTRAINT [FK__SWIFT_PRO__PACK___65EBFF70] FOREIGN KEY ([PACK_UNIT_BONUS]) REFERENCES [acsa].[SONDA_PACK_UNIT] ([PACK_UNIT]),
    CONSTRAINT [FK__SWIFT_PRO__PROMO__66E023A9] FOREIGN KEY ([PROMO_ID]) REFERENCES [acsa].[SWIFT_PROMO] ([PROMO_ID]),
    CONSTRAINT [UQ__SWIFT_PR__AAC8B892324325FC] UNIQUE NONCLUSTERED ([PROMO_ID] ASC, [CODE_SKU] ASC, [PACK_UNIT] ASC, [CODE_SKU_BONUS] ASC, [PACK_UNIT_BONUS] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PROMO_BONUS_BY_MULTIPLE_LAST_UPDATE]
    ON [acsa].[SWIFT_PROMO_BONUS_BY_MULTIPLE]([LAST_UPDATE] ASC);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PROMO_BONUS_BY_MULTIPLE_PROMO]
    ON [acsa].[SWIFT_PROMO_BONUS_BY_MULTIPLE]([PROMO_ID] ASC)
    INCLUDE([CODE_SKU], [PACK_UNIT], [MULTIPLE], [CODE_SKU_BONUS], [PACK_UNIT_BONUS], [BONUS_QTY]);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PROMO_BONUS_BY_MULTIPLE_PROMO_PROMO_ID_PACK_UNIT]
    ON [acsa].[SWIFT_PROMO_BONUS_BY_MULTIPLE]([PROMO_ID] ASC, [PACK_UNIT] ASC, [PACK_UNIT_BONUS] ASC)
    INCLUDE([CODE_SKU], [MULTIPLE], [CODE_SKU_BONUS], [BONUS_QTY]);

