CREATE TABLE [acsa].[SWIFT_FREQUENCY_BY_POLYGON] (
    [POLYGON_ID]   INT NOT NULL,
    [ID_FREQUENCY] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([POLYGON_ID] ASC, [ID_FREQUENCY] ASC),
    CONSTRAINT [FK__SWIFT_FRE__ID_FR__54C1736E] FOREIGN KEY ([ID_FREQUENCY]) REFERENCES [acsa].[SWIFT_FREQUENCY] ([ID_FREQUENCY]),
    CONSTRAINT [FK__SWIFT_FRE__POLYG__55B597A7] FOREIGN KEY ([POLYGON_ID]) REFERENCES [acsa].[SWIFT_POLYGON] ([POLYGON_ID])
);

