CREATE TABLE [acsa].[SWIFT_QUERY_LIST_BY_ROLE] (
    [QUERY_LIST_ROLE] INT          IDENTITY (1, 1) NOT NULL,
    [QUERY_LIST_ID]   INT          NOT NULL,
    [TEAM_ID]         NUMERIC (18) NOT NULL,
    PRIMARY KEY CLUSTERED ([QUERY_LIST_ID] ASC, [TEAM_ID] ASC)
);

