CREATE TABLE [acsa].[SWIFT_POLYGON_BY_ROUTE] (
    [ROUTE]           INT NOT NULL,
    [POLYGON_ID]      INT NOT NULL,
    [ID_FREQUENCY]    INT NULL,
    [IS_MULTIPOLYGON] INT DEFAULT ((0)) NOT NULL,
    [IS_MULTISELLER]  INT DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([ROUTE] ASC, [POLYGON_ID] ASC),
    CONSTRAINT [FK__SWIFT_POL__ID_FR__5A7A4CC4] FOREIGN KEY ([ID_FREQUENCY]) REFERENCES [acsa].[SWIFT_FREQUENCY] ([ID_FREQUENCY]),
    CONSTRAINT [FK__SWIFT_POL__POLYG__5B6E70FD] FOREIGN KEY ([POLYGON_ID]) REFERENCES [acsa].[SWIFT_POLYGON] ([POLYGON_ID]),
    CONSTRAINT [FK_SWIFT_POLYGON_BY_ROUTE_ROUTE] FOREIGN KEY ([ROUTE]) REFERENCES [acsa].[SWIFT_ROUTES] ([ROUTE]),
    CONSTRAINT [UC_SWIFT_POLYGON_BY_ROUTE_POLYGON_ID] UNIQUE NONCLUSTERED ([POLYGON_ID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_POLYGON_BY_ROUTE_ID_FREQUENCY]
    ON [acsa].[SWIFT_POLYGON_BY_ROUTE]([ID_FREQUENCY] ASC);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_POLYGON_BY_ROUTE_ROUTE]
    ON [acsa].[SWIFT_POLYGON_BY_ROUTE]([ROUTE] ASC);

