CREATE TABLE [acsa].[SWIFT_WAREHOUSE_BY_USER_WITH_ACCESS] (
    [USER_CORRELATIVE] INT          NOT NULL,
    [CODE_WAREHOUSE]   VARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([USER_CORRELATIVE] ASC, [CODE_WAREHOUSE] ASC),
    CONSTRAINT [FK__SWIFT_WAR__CODE___43C366A3] FOREIGN KEY ([CODE_WAREHOUSE]) REFERENCES [acsa].[SWIFT_WAREHOUSES] ([CODE_WAREHOUSE])
);

