CREATE TABLE [acsa].[SWIFT_PROMO] (
    [PROMO_ID]    INT           IDENTITY (1, 1) NOT NULL,
    [PROMO_NAME]  VARCHAR (250) NOT NULL,
    [PROMO_TYPE]  VARCHAR (50)  NOT NULL,
    [LAST_UPDATE] DATETIME      CONSTRAINT [DF__SWIFT_PRO__LAST___0FC23DAB] DEFAULT (getdate()) NOT NULL,
    CONSTRAINT [PK__SWIFT_PR__9A7B5816AD2CF195] PRIMARY KEY CLUSTERED ([PROMO_ID] ASC),
    CONSTRAINT [UQ_SWIFT_PROMO_PROMO_NAME] UNIQUE NONCLUSTERED ([PROMO_NAME] ASC, [PROMO_TYPE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PROMO_LAST_UPDATE]
    ON [acsa].[SWIFT_PROMO]([LAST_UPDATE] ASC);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_PROMO_PROMO_TYPE]
    ON [acsa].[SWIFT_PROMO]([PROMO_TYPE] ASC);

