CREATE TABLE [acsa].[SWIFT_PRICE_LIST_BY_CUSTOMER] (
    [CODE_PRICE_LIST] VARCHAR (50) NULL,
    [CODE_CUSTOMER]   VARCHAR (50) NOT NULL,
    [OWNER]           VARCHAR (50) NOT NULL,
    CONSTRAINT [UC_SWIFT_PRICE_LIST_BY_CUSTOMER_OWNER_CODE_CUSTOMER] UNIQUE NONCLUSTERED ([OWNER] ASC, [CODE_CUSTOMER] ASC)
);

