CREATE TABLE [acsa].[SWIFT_HISTORY_BY_PROMO] (
    [HISTORY_BY_PROMO_ID]         INT           IDENTITY (1, 1) NOT NULL,
    [DOC_SERIE]                   VARCHAR (100) NOT NULL,
    [DOC_NUM]                     INT           NOT NULL,
    [CODE_ROUTE]                  VARCHAR (50)  NOT NULL,
    [CODE_CUSTOMER]               VARCHAR (50)  NOT NULL,
    [HISTORY_DATETIME]            DATETIME      CONSTRAINT [DF__SWIFT_HIS__HISTO__2C938683] DEFAULT (getdate()) NOT NULL,
    [PROMO_ID]                    INT           NOT NULL,
    [PROMO_NAME]                  VARCHAR (50)  NOT NULL,
    [FREQUENCY]                   VARCHAR (50)  NOT NULL,
    [LAST_APPLIED]                INT           NOT NULL,
    [IS_POSTED]                   INT           NULL,
    [IS_POSTED_OFFLINE]           INT           NULL,
    [DEVICE_NETWORK_TYPE]         VARCHAR (50)  NULL,
    [SERVER_POSTED_DATETIME]      DATETIME      CONSTRAINT [DF__SWIFT_HIS__SERVE__2D87AABC] DEFAULT (getdate()) NULL,
    [SALES_ORDER_DOCUMENT_NUMBER] INT           CONSTRAINT [DF__SWIFT_HIS__SALES__2E7BCEF5] DEFAULT ((0)) NOT NULL,
    [SALES_ORDER_DOCUMENT_SERIES] VARCHAR (250) CONSTRAINT [DF__SWIFT_HIS__SALES__2F6FF32E] DEFAULT ('N/A') NOT NULL,
    CONSTRAINT [PK_SWIFT_HISTORY_BY_PROMO] PRIMARY KEY NONCLUSTERED ([HISTORY_BY_PROMO_ID] ASC),
    CONSTRAINT [UK_SWIFT_HISTORY_BY_PROMO_DOC_SERIE_DOC_NUM] UNIQUE CLUSTERED ([DOC_SERIE] ASC, [DOC_NUM] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_HISTORY_BY_PROMO_CODE_ROUTE]
    ON [acsa].[SWIFT_HISTORY_BY_PROMO]([CODE_CUSTOMER] ASC)
    INCLUDE([DOC_SERIE], [DOC_NUM], [CODE_ROUTE], [HISTORY_DATETIME], [PROMO_ID], [PROMO_NAME], [FREQUENCY], [IS_POSTED]);

