CREATE TABLE [acsa].[SWIFT_CHANNEL] (
    [CHANNEL_ID]          INT           IDENTITY (1, 1) NOT NULL,
    [CODE_CHANNEL]        VARCHAR (50)  NOT NULL,
    [NAME_CHANNEL]        VARCHAR (250) NOT NULL,
    [DESCRIPTION_CHANNEL] VARCHAR (250) NULL,
    [TYPE_CHANNEL]        VARCHAR (50)  NOT NULL,
    [LAST_UPDATE]         DATETIME      NULL,
    [LAST_UPDATE_BY]      VARCHAR (50)  NULL,
    CONSTRAINT [PK__SWIFT_CH__75DA08CD89A0BBAA] PRIMARY KEY CLUSTERED ([CHANNEL_ID] ASC),
    CONSTRAINT [UQ__SWIFT_CH__38C266B2DD14D5B5] UNIQUE NONCLUSTERED ([CODE_CHANNEL] ASC)
);


GO
CREATE NONCLUSTERED INDEX [IN_SWIFT_CHANNEL_TYPE_CHANNEL]
    ON [acsa].[SWIFT_CHANNEL]([TYPE_CHANNEL] ASC)
    INCLUDE([CHANNEL_ID], [CODE_CHANNEL], [NAME_CHANNEL], [DESCRIPTION_CHANNEL]);

