CREATE TABLE [acsa].[SWIFT_ERP_SELLER] (
    [SELLER_CODE] VARCHAR (50)  NOT NULL,
    [SELLER_NAME] VARCHAR (155) NOT NULL,
    CONSTRAINT [PK_SWIFT_ERP_SELLER] PRIMARY KEY CLUSTERED ([SELLER_CODE] ASC)
);

