

CREATE PROCEDURE [acsa].[SWIFT_GET_REPORT_MANIFEST]
@MANIFEST_HEADER INT
AS
SELECT DISTINCT
	A.MANIFEST_HEADER
	,A.CODE_MANIFEST_HEADER
	,A.COMMENTS
	,A.CREATED_DATE AS 'FECHA_CREACION'
	,A.LAST_UPDATE_BY AS 'USUARIO_CREADOR'
	,(
		SELECT COUNT(E.CODE_PICKING) FROM acsa.SWIFT_MANIFEST_DETAIL E WHERE E.CODE_MANIFEST_HEADER = A.MANIFEST_HEADER 
	) AS 'CANTIDAD_PEDIDOS'
	,B.NAME_DRIVER AS 'PILOTO_ASIGNADO'
	,C.PLATE_VEHICLE AS 'VEHICLE'
	,D.NAME_ROUTE AS 'GEO_RUTA'
	,C.PLATE_VEHICLE
	,B.LICENSE_DRIVER
FROM
	acsa.SWIFT_MANIFEST_HEADER AS A
LEFT OUTER JOIN
	acsa.SWIFT_DRIVERS AS B
ON A.CODE_DRIVER = B.CODE_DRIVER
LEFT OUTER JOIN
	acsa.SWIFT_VEHICLES AS C
ON A.CODE_VEHICLE = C.CODE_VEHICLE
LEFT OUTER JOIN
	acsa.SWIFT_ROUTES AS D
ON A.CODE_ROUTE = D.CODE_ROUTE
WHERE A.MANIFEST_HEADER = @MANIFEST_HEADER


SELECT DISTINCT
	A.MANIFEST_HEADER
	,B.CODE_PICKING AS 'NUMERO_PICKING'
	,B.REFERENCE
	,B.DOC_SAP_PICKING
	,C.NAME_CUSTOMER
	,ISNULL(C.ADRESS_CUSTOMER,'N/A') AS ADRESS_CUSTOMER
	,ISNULL(C.PHONE_CUSTOMER,'N/A') AS PHONE_CUSTOMER
	,CASE 
            WHEN B.[TYPE] = 'PICKING'
               THEN D.SCHEDULE_FOR
			--WHEN B.[TYPE] = 'INVOICE'
			--THEN G.DocDate
	END  AS 'FECHA_PROPUESTA'
	,CASE 
            WHEN B.[TYPE] = 'PICKING'
               THEN E.CODE_SKU
			--WHEN B.[TYPE] = 'INVOICE'
			--THEN  H.ItemCode COLLATE DATABASE_DEFAULT
	END  AS 'CODE_SKU'
	,CASE 
            WHEN B.[TYPE] = 'PICKING'
               THEN E.DESCRIPTION_SKU
			--WHEN B.[TYPE] = 'INVOICE'
			--THEN  H.[Dscription] COLLATE DATABASE_DEFAULT
	END  AS 'DESCRIPTION_SKU'
	,CASE 
            WHEN B.[TYPE] = 'PICKING'
               THEN E.SCANNED
			--WHEN B.[TYPE] = 'INVOICE'
			--THEN H.Quantity
	END  AS 'NO_SKU_ESCANEADOS'
	,CASE 
            WHEN B.[TYPE] = 'PICKING'
               THEN ISNULL(D.COMMENTS,'NINGUNA OBSERVACION')
			--WHEN B.[TYPE] = 'INVOICE'
			--THEN  ISNULL(G.Comments,'NINGUNA OBSERVACION') COLLATE DATABASE_DEFAULT
	END  AS 'OBSERVACIONES'
	--,F.TXN_SERIE AS SERIES_SIN_ORDENAR
	,CAST((SELECT X.TXN_SERIE + ', ' 
			FROM acsa.SWIFT_TXNS AS X 
			WHERE X.HEADER_REFERENCE = B.CODE_PICKING AND X.TXN_CODE_SKU = E.CODE_SKU
			FOR XML PATH('')) as varchar(max)) AS SERIES_ORDENADAS
	,CASE 
            WHEN B.[TYPE] = 'PICKING'
                --THEN COUNT(E.CODE_SKU)
				THEN E.SCANNED
			--WHEN B.[TYPE] = 'INVOICE'
			--	THEN SUM(H.Quantity)
	END  AS 'CANTIDAD'
	,CASE 
            WHEN B.[TYPE] = 'PICKING'
			--THEN 'VENDEDOR POR PICKING'
                THEN ISNULL((SELECT TOP 1 SELLER_NAME FROM OPENQUERY (ACSASERVER,'SELECT SE.SlpName as SELLER_NAME, PO.DocNum AS ERP_DOC
FROM         [SBO_ProyectosFinos].dbo.RDR1 AS POD INNER JOIN
                      [SBO_ProyectosFinos].dbo.ORDR AS PO ON PO.DocEntry = POD.DocEntry
					 INNER JOIN
					[SBO_ProyectosFinos].dbo.OSLP AS SE
					ON SE.SlpCode =  PO.SlpCode
WHERE  (PO.DocType = ''I'') and po.docstatus =''C'' ') WHERE ERP_DOC = B.DOC_SAP_PICKING),'N/A')
			WHEN B.[TYPE] = 'INVOICE'
			THEN 'VENDEDOR POR FACTURA'
				--THEN (SELECT SE.SlpName FROM OPENQUERY (ACSASERVER,'SELECT SlpName, SlpCode
				--	 FROM [SBO_ProyectosFinos].dbo.OSLP ') AS SE
				--	WHERE G.SlpCode =  SE.SlpCode) 
	END  AS 'SELLER_NAME'
FROM
	acsa.SWIFT_MANIFEST_HEADER AS A
LEFT OUTER JOIN
	acsa.SWIFT_MANIFEST_DETAIL AS B
ON A.MANIFEST_HEADER = B.CODE_MANIFEST_HEADER
LEFT OUTER JOIN
	acsa.SWIFT_VIEW_ALL_COSTUMER AS C
ON B.CODE_CUSTOMER = C.CODE_CUSTOMER
LEFT OUTER JOIN
	acsa.SWIFT_PICKING_HEADER AS D
ON B.CODE_PICKING = D.PICKING_HEADER
LEFT OUTER JOIN
	acsa.SWIFT_PICKING_DETAIL AS E
ON B.CODE_PICKING = E.PICKING_HEADER
LEFT OUTER JOIN
	acsa.SWIFT_TXNS AS F
ON E.CODE_SKU = F.TXN_CODE_SKU AND B.CODE_PICKING = F.HEADER_REFERENCE
--LEFT OUTER JOIN
--	SWIFT_INTERFACES.acsa.ERP_VIEW_INVOICE_HEADER AS G
--ON G.DocEntry = B.CODE_PICKING
--LEFT OUTER JOIN
--	SWIFT_INTERFACES.acsa.ERP_VIEW_INVOICE_DETAIL AS H
--ON G.DocEntry = H.DocEntry
WHERE A.MANIFEST_HEADER = @MANIFEST_HEADER
GROUP BY 
	A.MANIFEST_HEADER
	,B.CODE_PICKING
	,B.REFERENCE
	,B.DOC_SAP_PICKING
	,C.NAME_CUSTOMER
	,C.ADRESS_CUSTOMER
	,C.PHONE_CUSTOMER
	,D.SCHEDULE_FOR
	,E.CODE_SKU
	,E.DESCRIPTION_SKU
	,E.SCANNED
	,D.COMMENTS
	,B.[TYPE]
	--,G.DocDate
	--,H.ItemCode
	--,H.Dscription
	--,H.Quantity
	--,G.Comments
	--,G.SlpCode







