
CREATE PROCEDURE [acsa].[SWIFT_SP_GET_CUSTOMER_NO_ASOCIADO]	
@CUSTOMER INTEGER,
@CODE_CUSTOMER INTEGER,
@NAME_CUSTOMER VARCHAR
AS
SELECT *
 FROM [$(CICDSondaBD)].[acsa].[SWIFT_CUSTOMERS_NEW] AS CLIENTE
 WHERE  NOT EXISTS 
 (SELECT  1 
 from  [$(CICDSondaBD)].[acsa].[SWIFT_FREQUENCY_X_CUSTOMER] AS FRECUENCIA
 WHERE    CLIENTE.CODE_CUSTOMER=@CODE_CUSTOMER  )



