CREATE PROC [acsa].[SWIFT_SP_GET_PAYMENT_METHOD_CUSTOMER_ASSIGNED]
	@CODE_PAYMENT VARCHAR(50)
AS	
	SELECT C.*
	FROM [acsa].[SWIFT_PAYMENT_METHODS_BY_CUSTOMER] PC
		INNER JOIN acsa.SWIFT_VIEW_CUSTOMERS C ON C.CODE_CUSTOMER = PC.CODE_CUSTOMER
	WHERE PC.CODE_PAYMENT = @CODE_PAYMENT





