CREATE PROC [acsa].[SWIFT_GET_STATUS_INVENTORY_FOR_PICKING]
AS
	SELECT *
	INTO #RESERVED
	FROM acsa.[SWIFT_FN_GET_INVENTORY_RESERVED]()
	--
	SELECT *
	INTO #TEMP
	FROM [acsa].[SWIFT_FN_GET_INVENTORY_RESERVED_TEMP]()
	--
	SELECT
		INVENTORY = IDENTITY(int,1,1)
    	,A.SKU AS CODE_SKU
    	,MAX(A.SKU_DESCRIPTION) AS SKU_DESCRIPTION
    	,0 AS ON_HAND
    	,0 AS RESERVED
    	,(
      	  SUM(ON_HAND)-
      	  (
        	COALESCE(MAX(IR.QYT_RESERVED), 0)
        	)+
        	COALESCE(MAX(IRT.QYT_RESERVED),0)
    	) AS TO_SALE
	INTO #RESULT
	FROM acsa.SWIFT_INVENTORY A
	LEFT JOIN #RESERVED IR ON (A.SKU = IR.CODE_SKU)
	LEFT JOIN #TEMP IRT ON (A.SKU = IRT.CODE_SKU)
	WHERE A.ON_HAND > 0
		AND A.LAST_UPDATE_BY != 'BULK_DATA'
	GROUP BY A.SKU
	--ORDER BY A.SKU
	--
	SELECT * FROM #RESULT WHERE TO_SALE > 0

