-- =============================================
-- Autor:				rodrigo.gomez
-- Fecha de Creacion: 	12/28/2016 @ A-TEAM Sprint  
-- Description:			Obtiene las bodegas no asignadas más la bodega ya asignada al usuario por centro de distribución y usuario

/*
-- Ejemplo de Ejecucion:
				EXEC [acsa].[SWIFT_SP_GET_UNASSIGNED_SALE_WAREHOUSE_BY_DISTRIBUTION_CENTER_AND_LOGIN]
					@LOGIN = 'gerente@acsa'
					,@DISTRIBUTION_CENTER_ID = 1
*/
-- =============================================
CREATE PROCEDURE [acsa].[SWIFT_SP_GET_UNASSIGNED_SALE_WAREHOUSE_BY_DISTRIBUTION_CENTER_AND_LOGIN](
	@LOGIN VARCHAR(50) = NULL	
	,@DISTRIBUTION_CENTER_ID INT
)
AS
BEGIN
	SET NOCOUNT ON;
	--
	DECLARE @CORRELATIVE INT
	--
	SELECT @CORRELATIVE = CORRELATIVE FROM [acsa].[USERS] WHERE @LOGIN = [LOGIN]
	--
	SELECT DISTINCT
		[SW].[WAREHOUSE]
		,[SW].[CODE_WAREHOUSE]
		,[SW].[DESCRIPTION_WAREHOUSE]
		,[SW].[WEATHER_WAREHOUSE]
		,[SW].[STATUS_WAREHOUSE]
		,[SW].[LAST_UPDATE]
		,[SW].[LAST_UPDATE_BY]
		,[SW].[IS_EXTERNAL]
		,[SW].[BARCODE_WAREHOUSE]
		,[SW].[SHORT_DESCRIPTION_WAREHOUSE]
		,[SW].[TYPE_WAREHOUSE]
		,[SW].[ERP_WAREHOUSE]
		,[SW].[ADDRESS_WAREHOUSE]
		,[SW].[GPS_WAREHOUSE] 
	FROM [acsa].[SWIFT_WAREHOUSES] [SW]
	INNER JOIN [acsa].[SWIFT_WAREHOUSE_X_DISTRIBUTION_CENTER] [WDC] ON (
		[WDC].[CODE_WAREHOUSE] = [SW].[CODE_WAREHOUSE]
	)
	LEFT JOIN [acsa].[USERS] [U] ON (
		[U].[DEFAULT_WAREHOUSE] = [WDC].[CODE_WAREHOUSE]
	)
	WHERE [WDC].[DISTRIBUTION_CENTER_ID] = @DISTRIBUTION_CENTER_ID
		--AND	[U].[DEFAULT_WAREHOUSE] IS NULL
		
	UNION 

	SELECT 
		[SW].[WAREHOUSE]
		,[SW].[CODE_WAREHOUSE]
		,[SW].[DESCRIPTION_WAREHOUSE]
		,[SW].[WEATHER_WAREHOUSE]
		,[SW].[STATUS_WAREHOUSE]
		,[SW].[LAST_UPDATE]
		,[SW].[LAST_UPDATE_BY]
		,[SW].[IS_EXTERNAL]
		,[SW].[BARCODE_WAREHOUSE]
		,[SW].[SHORT_DESCRIPTION_WAREHOUSE]
		,[SW].[TYPE_WAREHOUSE]
		,[SW].[ERP_WAREHOUSE]
		,[SW].[ADDRESS_WAREHOUSE]
		,[SW].[GPS_WAREHOUSE]
	FROM [acsa].[SWIFT_WAREHOUSES] [SW]
	LEFT JOIN [acsa].[USERS] [U] ON (
		[U].[DEFAULT_WAREHOUSE] = [SW].[CODE_WAREHOUSE]
	)
	WHERE [U].[LOGIN] = @LOGIN
END

