CREATE PROC [acsa].[SWIFT_SP_GET_TRASFER_SYN]
@Login VARCHAR(50)
AS

UPDATE  [acsa].[SWIFT_TRANSFER_HEADER] SET
[STATUS] = 'EN_SINCRONIZACION'
WHERE [STATUS] IN ('PENDIENTE', 'EN_SINCRONIZACION')
AND SELLER_CODE = (SELECT TOP 1 RELATED_SELLER FROM [acsa].USERS 
WHERE [LOGIN] = @Login)

SELECT * 
FROM [acsa].[SWIFT_TRANSFER_HEADER]
WHERE [STATUS] IN ('PENDIENTE', 'EN_SINCRONIZACION')
AND SELLER_CODE = (SELECT TOP 1 RELATED_SELLER FROM [acsa].USERS 
WHERE [LOGIN] = @Login)
--AND B.SKU NOT IN( (SELECT COUNT_SKU FROM [acsa].SWIFT_CYCLE_COUNT_DETAIL WHERE COUNT_STATUS='PENDING'  AND COUNT_SKU IS NOT NULL) )

