CREATE PROCEDURE [acsa].[SWIFT_SP_GET_ROUTE_COMPLIANCE]
AS
BEGIN
	
	DROP INDEX IDX_SALES_DATE_COMPLIANCE ON acsa.[SWIFT_ROUTE_COMPLIANCE]

	DELETE FROM  acsa.[SWIFT_ROUTE_COMPLIANCE]
	WHERE [SCHEDULE_FOR] = CAST(GETDATE() AS DATE)
	
	SELECT
		[T].[TASK_ID]
	   ,[T].[TASK_TYPE]
	   ,[T].[SCHEDULE_FOR]
	   ,[T].[ASSIGEND_TO] AS [ASSIGNED_TO]
	   ,[T].[TASK_STATUS]
	   ,[T].[COSTUMER_CODE]
	   ,[T].[COSTUMER_NAME]
	   ,[T].[CUSTOMER_PHONE]
	   ,[T].[TASK_ADDRESS]
	   ,[T].[COMPLETED_SUCCESSFULLY]
	   ,[T].[REASON]
	   ,[T].[ACCEPTED_STAMP]
	   ,[T].[COMPLETED_STAMP]
	   ,[T].[ACCEPTED_STAMP]
	   ,[T].[COMPLETED_STAMP]
	   INTO #TASKS
	  FROM  [acsa].[SWIFT_TASKS] [T]
	  WHERE [T].[TASK_TYPE] NOT IN ('RECEPTION', 'PICKING', 'DRAFT')
	  AND CAST([T].[SCHEDULE_FOR] AS DATE)= CAST(GETDATE() AS DATE)

	  SELECT
	    [H].[TASK_ID]
	   ,[H].[TOTAL_AMOUNT]
	   INTO	#SALESORDER
	  FROM [acsa].[SONDA_SALES_ORDER_HEADER] [H]
	  WHERE [H].IS_READY_TO_SEND = 1
		AND CAST([H].[POSTED_DATETIME] AS DATE)= CAST(GETDATE() AS DATE)
	  GROUP BY [H].[TASK_ID], [H].[TOTAL_AMOUNT]

	  INSERT INTO [acsa].[SWIFT_ROUTE_COMPLIANCE]
	  		(
	  			[TASK_ID]
	  			,[TASK_TYPE]
	  			,[SCHEDULE_FOR]
	  			,[ASSIGNED_TO]
	  			,[NAME_USER]
	  			,[CODE_ROUTE]
	  			,[NAME_ROUTE]
	  			,[TASK_STATUS]
	  			,[COSTUMER_CODE]
	  			,[COSTUMER_NAME]
	  			,[CUSTOMER_PHONE]
	  			,[TASK_ADDRESS]
	  			,[COMPLETED_STATUS]
	  			,[ACCEPTED_STAMP]
	  			,[COMPLETED_STAMP]
	  			,[LAPSE_MINUTES]
	  			,[TOTAL_AMOUNT]
	  		)
	   SELECT
		[T].[TASK_ID]
	   ,CASE [T].[TASK_TYPE]
		  WHEN 'PRESALE' THEN 'PREVENTA'
		  WHEN 'TAKE_INVENTORY' THEN 'TOMA DE INVENTARIO'
		  WHEN 'SALE' THEN 'VENTA DIRECTA'
		  WHEN 'DELIVERY' THEN 'ENTREGA'
		  ELSE [T].[TASK_TYPE]
		END [TASK_TYPE]
	   ,[T].[SCHEDULE_FOR]
	   ,[T].[ASSIGEND_TO] AS [ASSIGNED_TO]
	   ,[U].[NAME_USER]
	   ,[R].[CODE_ROUTE]
	   ,[R].[NAME_ROUTE]
	   ,CASE [T].[TASK_STATUS]
		  WHEN 'ASSIGNED' THEN 'ASIGNADA'
		  WHEN 'ACCEPTED' THEN 'ACEPTADA'
		  WHEN 'COMPLETED' THEN 'COMPLETADA'
		  ELSE [T].[TASK_STATUS]
		END [TASK_STATUS]
	   ,[T].[COSTUMER_CODE]
	   ,[T].[COSTUMER_NAME]
	   ,[T].[CUSTOMER_PHONE]
	   ,[T].[TASK_ADDRESS]
	   ,CASE
		  WHEN CAST([T].[COMPLETED_SUCCESSFULLY] AS VARCHAR) IS NULL THEN 'SIN OPERAR'
		  WHEN CAST([T].[COMPLETED_SUCCESSFULLY] AS VARCHAR) = '1' THEN 'REALIZO GESTION'
		  ELSE [T].[REASON]
		END [COMPLETED_STATUS]
	   ,[T].[ACCEPTED_STAMP]
	   ,[T].[COMPLETED_STAMP]
	   ,ABS(DATEDIFF(MINUTE, [T].[ACCEPTED_STAMP], [T].[COMPLETED_STAMP])) LAPSE_MINUTES 
	   ,[H].[TOTAL_AMOUNT]
	  FROM  #TASKS [T]
	  INNER	JOIN [acsa].[USERS] [U]
		ON (
		  [T].[ASSIGEND_TO] = [U].[LOGIN]
		  )
	  INNER	JOIN [acsa].[SWIFT_ROUTES] [R]
		ON (
		  [U].[SELLER_ROUTE] = [R].[CODE_ROUTE]
		  )
	  LEFT JOIN #SALESORDER [H]
		ON (
		  [H].[TASK_ID]=[T].[TASK_ID]
		)

	CREATE INDEX IDX_SALES_DATE_COMPLIANCE ON acsa.[SWIFT_ROUTE_COMPLIANCE] (SCHEDULE_FOR)

END
