-- Autor:				pedro.loukota
-- Fecha de Creacion: 	11-11-2015
-- Description:			Obtiene Bodegas no asignadas a clientes
/*
-- Ejemplo de Ejecucion:				
				select [acsa].SWIFT_SP_GET_NOTASIGN_WAREHOUSES
*/
CREATE PROCEDURE [acsa].[SWIFT_SP_GET_NOTASIGN_WAREHOUSES]

@LOGIN varchar(50)
AS
BEGIN

DECLARE @TOTALASSIGN INT 

SELECT @TOTALASSIGN =  COUNT(*) FROM [acsa].[SWIFT_WAREHOUSES] 
	
			WHERE [acsa].[SWIFT_WAREHOUSES].[CODE_WAREHOUSE] NOT IN 
			
			(SELECT DEFAULT_WAREHOUSE FROM  [acsa].[USERS] WHERE [acsa].[USERS].CORRELATIVE != @LOGIN OR [acsa].[USERS].LOGIN = NULL)


IF @TOTALASSIGN > 0
 BEGIN

		    SELECT  * FROM [acsa].[SWIFT_WAREHOUSES] 
	
			WHERE [acsa].[SWIFT_WAREHOUSES].[CODE_WAREHOUSE] NOT IN 
			
			(SELECT DEFAULT_WAREHOUSE FROM  [acsa].[USERS] WHERE [acsa].[USERS].CORRELATIVE != @LOGIN OR [acsa].[USERS].LOGIN = NULL)

		UNION	
			SELECT  * FROM [acsa].[SWIFT_WAREHOUSES] 
	
			WHERE [acsa].[SWIFT_WAREHOUSES].[CODE_WAREHOUSE]  IN 
			
			(SELECT DEFAULT_WAREHOUSE FROM  [acsa].[USERS] WHERE [acsa].[USERS].CORRELATIVE = @LOGIN)
			
		ORDER BY [acsa].[SWIFT_WAREHOUSES].[DESCRIPTION_WAREHOUSE]			
			
END


IF @TOTALASSIGN = 0
 BEGIN

		    SELECT  * FROM [acsa].[SWIFT_WAREHOUSES] 
	
END


END

