-- =============================================
-- Autor:				alberto.ruiz
-- Fecha de Creacion: 	13-04-2016
-- Description:			Crea detalle de la orden de venta

/*
-- EJEMPLO DE EJECUCION: 
		EXEC [acsa].[SWIFT_SP_GET_PRESALE_SKU_BY_PRICE_LIST]
			@LOGIN = 'RUDI@acsa'
			,@CODE_PRICE_LIST = '1'
*/		
-- =============================================
CREATE PROCEDURE [acsa].[SWIFT_SP_GET_PRESALE_SKU_BY_PRICE_LIST]
		@LOGIN VARCHAR(50)
		,@CODE_PRICE_LIST VARCHAR(50)
AS
BEGIN
	SET NOCOUNT ON;
	--

	SELECT
    	I.WAREHOUSE
    	,I.SKU
    	,MAX(I.SKU_DESCRIPTION) SKU_DESCRIPTION
    	,SUM(I.ON_HAND) AS ON_HAND
    	,ISNULL(IS_COMITED, 0) AS IS_COMITED
	INTO #SWIFT_VIEW_PRESALE_SKU
  	FROM [acsa].[SONDA_IS_COMITED_BY_WAREHOUSE] CW
    LEFT JOIN [acsa].[SWIFT_INVENTORY] I ON (
      	I.WAREHOUSE = CW.CODE_WAREHOUSE
      	AND I.SKU = CW.[CODE_SKU]
    )
  	GROUP BY WAREHOUSE, SKU,IS_COMITED


	SELECT
		S.SKU
		,S.SKU_DESCRIPTION
		,P.COST
		,CAST(S.ON_HAND AS INT) ON_HAND
		,CAST(S.IS_COMITED AS INT) IS_COMITED
		,CAST((S.ON_HAND - S.IS_COMITED) AS INT) DIFERENCE
	FROM acsa.[USERS] U
	INNER JOIN #SWIFT_VIEW_PRESALE_SKU S ON (U.PRESALE_WAREHOUSE = S.WAREHOUSE)
	INNER JOIN acsa.[SWIFT_PRICE_LIST_BY_SKU] P ON (S.SKU = P.CODE_SKU)
	WHERE U.[LOGIN] = @LOGIN
		AND P.COST > 0
		AND [P].[CODE_PRICE_LIST] = @CODE_PRICE_LIST
END




