CREATE PROCEDURE [acsa].[SWIFT_DELETE_TEMP_PICKING]
@HEADER_NUMBER_TEMP_PICKING INT
AS

EXEC acsa.SWIFT_INSERT_IN_TRANSAXION_AND_TASK_PICKING

DELETE acsa.SWIFT_TEMP_PICKING_HEADER --WHERE PICKING_HEADER = @HEADER_NUMBER_TEMP_PICKING
DELETE acsa.SWIFT_TEMP_PICKING_DETAIL --WHERE PICKING_HEADER = @HEADER_NUMBER_TEMP_PICKING
 










