-- =============================================
-- Autor:				alberto.ruiz
-- Fecha de Creacion: 	08-Feb-17 @ A-TEAM Sprint Chatuluka 
-- Description:			SP que borra 

/*
-- Ejemplo de Ejecucion:
				SELECT * FROM [acsa].[SWIFT_TRADE_AGREEMENT_BY_COMBO_BONUS_RULE]
				--
				EXEC [acsa].[SWIFT_SP_DELETE_TRADE_AGREEMENT_BY_COMBO_BONUS_RULE]
					@TRADE_AGREEMENT_BONUS_RULE_BY_COMBO_ID = 2
				-- 
				SELECT * FROM [acsa].[SWIFT_TRADE_AGREEMENT_BY_COMBO_BONUS_RULE]
*/
-- =============================================
CREATE PROCEDURE [acsa].[SWIFT_SP_DELETE_TRADE_AGREEMENT_BY_COMBO_BONUS_RULE](
	@TRADE_AGREEMENT_ID INT
	,@COMBO_ID INT
)
AS
BEGIN
	SET NOCOUNT ON;
	--
	DECLARE @TRADE_AGREEMENT_BONUS_RULE_BY_COMBO_ID INT
	BEGIN TRY
		SELECT TOP 1 @TRADE_AGREEMENT_BONUS_RULE_BY_COMBO_ID = [TAB].[TRADE_AGREEMENT_BONUS_RULE_BY_COMBO_ID]
		FROM [acsa].[SWIFT_TRADE_AGREEMENT_BY_BONUS_RULE] [TAB]
		INNER JOIN [acsa].[SWIFT_TRADE_AGREEMENT_BY_COMBO_BONUS_RULE] [TAR] ON (
			[TAR].[TRADE_AGREEMENT_BONUS_RULE_BY_COMBO_ID] = [TAB].[TRADE_AGREEMENT_BONUS_RULE_BY_COMBO_ID]
		)
		WHERE [TAB].[TRADE_AGREEMENT_ID] = @TRADE_AGREEMENT_ID
			AND [TAR].[COMBO_ID] = @COMBO_ID
		--
		DELETE FROM [acsa].[SWIFT_TRADE_AGREEMENT_BY_BONUS_RULE]
		WHERE [TRADE_AGREEMENT_BONUS_RULE_BY_COMBO_ID] = @TRADE_AGREEMENT_BONUS_RULE_BY_COMBO_ID
		--
		DELETE FROM [acsa].[SWIFT_TRADE_AGREEMENT_BY_COMBO_BONUS_RULE]
		WHERE [TRADE_AGREEMENT_BONUS_RULE_BY_COMBO_ID] = @TRADE_AGREEMENT_BONUS_RULE_BY_COMBO_ID
		--
		SELECT  1 as Resultado , 'Proceso Exitoso' Mensaje ,  0 Codigo, '' DbData
	END TRY
	BEGIN CATCH
		SELECT  -1 as Resultado
		,CASE CAST(@@ERROR AS VARCHAR)
			WHEN  '547' THEN 'El combo tiene bonificaciones asociadas'
			ELSE ERROR_MESSAGE()
		END Mensaje 
		,@@ERROR Codigo 
	END CATCH
END
