CREATE PROCEDURE [acsa].[SWIFT_SP_DELETECLASSIFICATION]
@CLASSIFICATION INT,
@pResult varchar(250) OUTPUT
AS

DECLARE @NAME_CLASSIFICATION VARCHAR(50)
DECLARE @VALUE_TEXT VARCHAR(50)
DECLARE @MPC01 VARCHAR(50)
SET @NAME_CLASSIFICATION = (SELECT NAME_CLASSIFICATION FROM acsa.SWIFT_CLASSIFICATION WHERE CLASSIFICATION = @CLASSIFICATION)
SET @VALUE_TEXT = (SELECT VALUE_TEXT_CLASSIFICATION FROM acsa.SWIFT_CLASSIFICATION WHERE CLASSIFICATION = @CLASSIFICATION)
SET @MPC01 = (SELECT MPC01 FROM acsa.SWIFT_CLASSIFICATION WHERE CLASSIFICATION = @CLASSIFICATION)
IF ((SELECT COUNT(A.WEATHER_WAREHOUSE) FROM acsa.SWIFT_WAREHOUSES AS A WHERE A.WEATHER_WAREHOUSE =  @CLASSIFICATION )
+ (SELECT COUNT(B.CLASSIFICATION_LOCATION) FROM acsa.SWIFT_LOCATIONS AS B WHERE B.CLASSIFICATION_LOCATION = @CLASSIFICATION  )
+ (SELECT COUNT(C.CLASSIFICATION_SKU) FROM acsa.SWIFT_SKU AS C WHERE C.CLASSIFICATION_SKU = @CLASSIFICATION  )
+ (SELECT COUNT(D.CLASSIFICATION_CUSTOMER) FROM acsa.SWIFT_CUSTOMERS AS D WHERE D.CLASSIFICATION_CUSTOMER = @CLASSIFICATION  )
+ (SELECT COUNT(E.CLASSIFICATION_PROVIDER) FROM acsa.SWIFT_PROVIDERS AS E WHERE E.CLASSIFICATION_PROVIDER = @CLASSIFICATION  )
+ (SELECT COUNT(F.CLASSIFICATION_VEHICLE) FROM acsa.SWIFT_VEHICLES AS F WHERE F.CLASSIFICATION_VEHICLE = @CLASSIFICATION  )
+ (SELECT COUNT(G.TYPE_RECEPTION) FROM acsa.SWIFT_RECEPTION_HEADER AS G WHERE G.TYPE_RECEPTION = @MPC01  )
+ (SELECT COUNT(H.CLASSIFICATION_PICKING) FROM acsa.SWIFT_PICKING_HEADER AS H WHERE H.CLASSIFICATION_PICKING = @CLASSIFICATION  )
+ (SELECT COUNT(I.[USER_TYPE]) FROM acsa.USERS AS I WHERE I.[USER_TYPE] = @NAME_CLASSIFICATION )
) = 0
BEGIN 
	DELETE FROM SWIFT_CLASSIFICATION WHERE CLASSIFICATION=@CLASSIFICATION
	SELECT @pResult = ''
END
ELSE
	BEGIN
		SELECT @pResult = 'El dato no se puede eliminar debido a que está siendo utilizado'
	END



