-- Modificacion 7/20/2018 @ A-Team Sprint G-Force@Gato
					-- diego.as
					-- Se cambia "[MPC01] [ACCOUNT_BANK]" por 

CREATE VIEW [acsa].[SONDA_VIEW_BANK_ACCOUNTS]
AS
	SELECT
		[VALUE_TEXT_CLASSIFICATION] + [NAME_CLASSIFICATION] AS [ACCOUNT_BASE]
		,[NAME_CLASSIFICATION] [ACCOUNT_NAME]
		,[VALUE_TEXT_CLASSIFICATION] [ACCOUNT_NUMBER]
		,[NAME_CLASSIFICATION] [ACCOUNT_BANK]
	FROM
		[ACSA].[SWIFT_CLASSIFICATION]
	WHERE
		[GROUP_CLASSIFICATION] = 'BANK_ACCOUNTS';

