CREATE VIEW [acsa].[SWIFT_VIEW_PRESALE_SKU]
AS
	SELECT
    	I.WAREHOUSE
    	,I.SKU
    	,MAX(I.SKU_DESCRIPTION) SKU_DESCRIPTION
    	,SUM(I.ON_HAND) AS ON_HAND
    	,ISNULL(IS_COMITED, 0) AS IS_COMITED
  	FROM [acsa].[SONDA_IS_COMITED_BY_WAREHOUSE] CW
    LEFT JOIN [acsa].[SWIFT_INVENTORY] I ON (
      	I.WAREHOUSE = CW.CODE_WAREHOUSE
      	AND I.SKU = CW.[CODE_SKU]
    )
    where i.ON_HAND>0
  	GROUP BY WAREHOUSE, SKU,IS_COMITED

