

CREATE VIEW [acsa].[SWIFT_VIEW_ALL_PROVIDERS] 
AS

SELECT
  CAST(PROVIDER AS VARCHAR) PROVIDER,
  CODE_PROVIDER,
  NAME_PROVIDER,
  CLASSIFICATION_PROVIDER,
  CONTACT_PROVIDER,
  0 FROM_ERP
FROM [acsa].SWIFT_PROVIDERS
UNION
SELECT
  [ERP].[PROVIDER]   PROVIDER,
  [ERP].CODE_PROVIDER  CODE_PROVIDER,
  [ERP].NAME_PROVIDER  NAME_PROVIDER,
  [ERP].CLASSIFICATION_PROVIDER  CLASSIFICATION_PROVIDER,
  [ERP].CONTACT_PROVIDER  CONTACT_PROVIDER,
  [ERP].FROM_ERP FROM_ERP
FROM 
[$(CICDInterfacesBD)].[acsa].ERP_VIEW_PROVIDERS [ERP]

