
-- =============================================
-- Autor:				rudi.garcia
-- Fecha de Creacion: 	21/07/2017 @ Reborn-TEAM Sprint Bearbeitung
-- Description:			Se agregon los siguientes campos [DEPARTAMENT], [MUNICIPALITY], [COLONY]

/*
-- Ejemplo de Ejecucion:
		SELECT * FROM [acsa].SWIFT_VIEW_CUSTOMERS
*/

CREATE VIEW [acsa].[SWIFT_VIEW_CUSTOMERS]
AS SELECT
  CAST(A.CUSTOMER AS VARCHAR) CUSTOMER
 ,A.CODE_CUSTOMER 
 ,A.NAME_CUSTOMER
 ,B.NAME_CLASSIFICATION
 ,A.CONTACT_CUSTOMER 
 ,C.NAME_ROUTE
 ,A.PHONE_CUSTOMER 
 ,A.SELLER_DEFAULT_CODE 
 ,A.CREDIT_LIMIT 
 ,0 FROM_ERP
 ,1 AS PRIORIDAD
 ,NULL AS RGA_CODE
 ,NULL AS [DEPARTAMENT]
 ,NULL AS [MUNICIPALITY]
 ,NULL AS [COLONY]
 ,[A].[GPS]  AS GPS
FROM [acsa].SWIFT_CUSTOMERS AS A
LEFT OUTER JOIN [acsa].SWIFT_CLASSIFICATION AS B
  ON A.CLASSIFICATION_CUSTOMER = B.CLASSIFICATION
LEFT OUTER JOIN [acsa].SWIFT_ROUTES AS C
  ON A.CODE_ROUTE = C.CODE_ROUTE
WHERE (ISNULL(B.GROUP_CLASSIFICATION , 'CUSTOMER') = 'CUSTOMER')
UNION
SELECT
  CUSTOMER  CUSTOMER
 ,CODE_CUSTOMER  CODE_CUSTOMER
 ,NAME_CUSTOMER  NAME_CUSTOMER
 ,NAME_CLASSIFICATION  NAME_CLASSIFICATION
 ,CONTACT_CUSTOMER  CONTACT_CUSTOMER
 ,NAME_ROUTE  NAME_ROUTE
 ,PHONE_CUSTOMER  PHONE_CUSTOMER
 ,SELLER_DEFAULT_CODE  AS SELLER_DEFAULT_CODE
 ,CREDIT_LIMIT AS CREDIT_LIMIT
 ,FROM_ERP FROM_ERP
 ,1 AS PRIORIDAD
 ,RGA_CODE
 ,[DEPARTAMENT]
 ,[MUNICIPALITY]
 ,[COLONY]
 ,[GPS]
FROM [$(CICDInterfacesBD)].[acsa].[ERP_VIEW_COSTUMER]
