-- =============================================
-- Autor:				diego.as
-- Fecha de Creacion: 	7/10/2017 @ A-TEAM Sprint  
-- Description:			SP PARA ACTUALIZAR LAS SO QUE TENGAN IS_READY_TO_SEND = 0 EN BASE A LA ZONA Y OPERADOR DE POSTEO

/*
-- Ejemplo de Ejecucion:
				EXEC [acsa].[UPDATE_SALES_ORDER]
				@WAREHOUSE = 'R006'
				,@POSTED_BY = 'TEC0003@acsa'
*/
-- =============================================
CREATE PROCEDURE [acsa].[UPDATE_SALES_ORDER](
	@WAREHOUSE VARCHAR(100)
	, @POSTED_BY VARCHAR(100)
	, @QTY_CLIENTS_TO_VALIDATE INT = NULL
)
AS
BEGIN
	SET NOCOUNT ON;
	--
	DECLARE @CLIENT_TO_VALIDATE VARCHAR(250) = NULL
		,@SALES_ORDER_ID_TO_VALIDATE INT = NULL
		,@SALES_ORDERS_WITH_IS_READY_TO_SEND INT = 0
		,@TOTAL_AMOUNT_HEADER MONEY = 0
		,@TOTAL_AMOUNT_DETAIL MONEY = 0;

	DECLARE @CLIENTS_TO_VALIDATE TABLE (
		CLIENT_ID VARCHAR(250)
	);

	IF(@QTY_CLIENTS_TO_VALIDATE IS NOT NULL)
	BEGIN 
		INSERT INTO @CLIENTS_TO_VALIDATE
		(
			CLIENT_ID
		)
		SELECT DISTINCT TOP 1 CLIENT_ID
		FROM acsa.SONDA_SALES_ORDER_HEADER WITH (NOLOCK)
		where POSTED_DATETIME>= format (getdate(),'yyyyMMdd')
		AND is_void=0
		AND WAREHOUSE=@WAREHOUSE
		AND POSTED_BY=@POSTED_BY
	END
	ELSE BEGIN
		INSERT INTO @CLIENTS_TO_VALIDATE
		(
			CLIENT_ID
		)
		SELECT DISTINCT CLIENT_ID
		FROM acsa.SONDA_SALES_ORDER_HEADER WITH (NOLOCK)
		where POSTED_DATETIME>= format (getdate(),'yyyyMMdd')
		AND is_void=0
		AND WAREHOUSE=@WAREHOUSE
		AND POSTED_BY=@POSTED_BY
	END

	WHILE EXISTS(SELECT TOP 1 1 FROM @CLIENTS_TO_VALIDATE)
	BEGIN
		SELECT TOP 1 @CLIENT_TO_VALIDATE = CLIENT_ID 
		FROM @CLIENTS_TO_VALIDATE
	
		IF(@CLIENT_TO_VALIDATE IS NOT NULL)
		BEGIN
			-- SELECCIONA LA ORDEN DE VENTA A VALIDAR
			SELECT TOP 1
			@SALES_ORDER_ID_TO_VALIDATE = SOH.[SALES_ORDER_ID]
			,@TOTAL_AMOUNT_HEADER = SOH.[TOTAL_AMOUNT]
			,@TOTAL_AMOUNT_DETAIL = SUM(SOD.[TOTAL_LINE])
			FROM acsa.[SONDA_SALES_ORDER_HEADER] AS SOH
			INNER JOIN [acsa].[SONDA_SALES_ORDER_DETAIL] AS SOD
			ON([SOH].[SALES_ORDER_ID] = [SOD].[SALES_ORDER_ID])
			WHERE [SOH].[CLIENT_ID] = @CLIENT_TO_VALIDATE
			AND [SOH].[POSTED_DATETIME] >= format (getdate(),'yyyyMMdd')
			GROUP BY SOH.[SALES_ORDER_ID]
				, SOH.[IS_READY_TO_SEND]
				, SOH.[CLIENT_ID]
				, SOH.[TOTAL_AMOUNT]
			ORDER BY [SOH].[SALES_ORDER_ID] ASC
		
			--OBTIENE LA CANTIDAD DE ORDENES DE VENTA EN IS_READY_TO_SEND = 1
			SELECT @SALES_ORDERS_WITH_IS_READY_TO_SEND = COUNT([SALES_ORDER_ID]) 
			FROM acsa.[SONDA_SALES_ORDER_HEADER] 
			WHERE [CLIENT_ID] = @CLIENT_TO_VALIDATE
			AND [IS_READY_TO_SEND] = 1
			AND [POSTED_DATETIME] >= format (getdate(),'yyyyMMdd')
		
			--VALIDA SI NO TIENE ORDENES DE VENTA CON IS_READY_TO_SEND = 1
			IF(@SALES_ORDERS_WITH_IS_READY_TO_SEND = 0)
			BEGIN
				UPDATE acsa.[SONDA_SALES_ORDER_HEADER]
				SET IS_READY_TO_SEND = 1
				WHERE SALES_ORDER_ID = @SALES_ORDER_ID_TO_VALIDATE
			END
			

			PRINT('SO VALIDADA = ' + CAST(@SALES_ORDER_ID_TO_VALIDATE AS VARCHAR))

			-- ELIMINA EL CLIENTE
			DELETE FROM @CLIENTS_TO_VALIDATE WHERE CLIENT_ID = @CLIENT_TO_VALIDATE
		END
	END
END
