CREATE PROC [acsa].[SWIFT_SP_GET_NEXT_SEQUENCE]
@SEQUENCE_NAME VARCHAR(50),
@pResult NUMERIC(18,0) OUTPUT
AS
--STORED PROCEDURE QUE DEVUELVE UNA RESPUESTA
DECLARE @COUNT INT
SET  @COUNT = (SELECT COUNT([SEQUENCE_NAME]) FROM [acsa].[SWIFT_SEQUENCES] WHERE [SEQUENCE_NAME] = @SEQUENCE_NAME)

IF(@COUNT = 0)
BEGIN
	INSERT INTO [acsa].[SWIFT_SEQUENCES] ([SEQUENCE_NAME], [CURRENT_NUMBER])
	VALUES
	(@SEQUENCE_NAME, 1)
	SET @pResult = 1
END
ELSE
BEGIN
	SET @pResult = (SELECT TOP 1 [CURRENT_NUMBER] FROM [acsa].[SWIFT_SEQUENCES] WHERE [SEQUENCE_NAME] = @SEQUENCE_NAME ORDER BY [CURRENT_NUMBER] DESC) + 1
	UPDATE [acsa].[SWIFT_SEQUENCES] SET [CURRENT_NUMBER] = @pResult WHERE [SEQUENCE_NAME] = @SEQUENCE_NAME
END


